BALL_RADIUS = 200
BALL_CONV_LAYERS = 3
EPOCHS = 1000
LEARNING_RATE = 0.0001
BATCH_SIZE = 200000
UNKNOWN = "randomize"
# UNKNOWN = "neutral"
SELF_LOOPS = None  # Means all
# SELF_LOOPS = [("chunk","precedes","chunk"),("chunk", "follows", "chunk"),("chunk", "pointed_to_by", "chunk")]
# SELF_LOOPS = "self"
